# Generated by Django 4.2.2 on 2023-07-28 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='adresse_ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='categorie_complete',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='code_materiel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='commentaire',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='date_depart_user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='date_installation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='date_livraison',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='date_premiere_installation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='date_sortie',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='departement',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='dernier_inventaire_discovery',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='dernier_inventaire_physique',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='dernier_login_connexion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='emplacement',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='id_user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='localisation_dernier_niveau',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='marque',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='memoire',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='modele',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='numero_serie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='statut',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='askit',
            name='utilisateur_principal',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='antivirus_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='device_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='device_ips',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='exposure_level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='first_seen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='health_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='is_aad_joined',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='last_device_update',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='managed_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='onboarding_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='os_distribution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='os_platform',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='os_version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='risk_level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='defender',
            name='windows_10_version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sap',
            name='amortissement_fin_ex',
            field=models.CharField(max_length=255, null=True, verbose_name='Amo.fin.ex.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='cat_immo',
            field=models.CharField(max_length=255, null=True, verbose_name='Cat.immo'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='centre',
            field=models.CharField(max_length=255, null=True, verbose_name='Centre'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='cod_am',
            field=models.CharField(max_length=255, null=True, verbose_name='CodAm'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='code_designat',
            field=models.CharField(max_length=255, null=True, verbose_name='Code désignat.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='comment_invent',
            field=models.CharField(max_length=255, null=True, verbose_name='Comment.invent.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='compte_cap',
            field=models.CharField(max_length=255, null=True, verbose_name='Compte CAP'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='date_inv',
            field=models.DateField(null=True, verbose_name='Date inv.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='debut_ad',
            field=models.DateField(null=True, verbose_name='Début AD'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='designation_immobilisatio1',
            field=models.CharField(max_length=255, null=True, verbose_name="Désignation de l'immobilisatio"),
        ),
        migrations.AlterField(
            model_name='sap',
            name='designation_immobilisatio2',
            field=models.CharField(max_length=255, null=True, verbose_name="Désignation de l'immobilisatio"),
        ),
        migrations.AlterField(
            model_name='sap',
            name='dev_amortissement_fin_ex',
            field=models.CharField(max_length=255, null=True, verbose_name='Dev.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='dev_val_acq_fin_ex',
            field=models.CharField(max_length=255, null=True, verbose_name='Dev.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='dev_val_cpt_fin_ex',
            field=models.CharField(max_length=255, null=True, verbose_name='Dev.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='dev_valeur_d_origine',
            field=models.CharField(max_length=255, null=True, verbose_name='Dev.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='dev_valeur_man_patr',
            field=models.CharField(max_length=255, null=True, verbose_name='Dev.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='disponibilite',
            field=models.CharField(max_length=255, null=True, verbose_name='Disponibilité'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='division',
            field=models.CharField(max_length=255, null=True, verbose_name='Div.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='doma',
            field=models.CharField(max_length=255, null=True, verbose_name='DomA'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='fabricant_immobilisation',
            field=models.CharField(max_length=255, null=True, verbose_name="Fabricant de l'immobilisation"),
        ),
        migrations.AlterField(
            model_name='sap',
            name='fournisseur1',
            field=models.CharField(max_length=255, null=True, verbose_name='Fourn.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='fournisseur2',
            field=models.CharField(max_length=255, null=True, verbose_name='Fournisseur'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='immo_d_orig',
            field=models.CharField(max_length=255, null=True, verbose_name="Immo.d'orig."),
        ),
        migrations.AlterField(
            model_name='sap',
            name='immobilis',
            field=models.CharField(max_length=255, null=True, verbose_name='Immobilis.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='local',
            field=models.CharField(max_length=255, null=True, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='localisat',
            field=models.CharField(max_length=255, null=True, verbose_name='Localisat.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='mise_hs',
            field=models.CharField(max_length=255, null=True, verbose_name='Mise h.s.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='mise_serv',
            field=models.CharField(max_length=255, null=True, verbose_name='Mise serv.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='mo',
            field=models.CharField(max_length=255, null=True, verbose_name='Mo'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='n_immatric',
            field=models.CharField(max_length=255, null=True, verbose_name="N° d'immatric."),
        ),
        migrations.AlterField(
            model_name='sap',
            name='n_projet_investissement',
            field=models.CharField(max_length=255, null=True, verbose_name="N° de projet d'investissement"),
        ),
        migrations.AlterField(
            model_name='sap',
            name='n_regr_immobilisation',
            field=models.CharField(max_length=255, null=True, verbose_name='N°regr.immo.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='n_s',
            field=models.CharField(max_length=255, null=True, verbose_name='NºS.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='n_s_iec',
            field=models.CharField(max_length=255, null=True, verbose_name='N°S. IEC'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='numero_inventaire',
            field=models.CharField(max_length=255, null=True, verbose_name="Numéro d'inventaire"),
        ),
        migrations.AlterField(
            model_name='sap',
            name='per',
            field=models.CharField(max_length=255, null=True, verbose_name='Pér'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='quantite',
            field=models.CharField(max_length=255, null=True, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='uq',
            field=models.CharField(max_length=255, null=True, verbose_name='UQ'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='ut',
            field=models.CharField(max_length=255, null=True, verbose_name='Ut.'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='val_acq_fin_ex',
            field=models.CharField(max_length=255, null=True, verbose_name='ValAcqFinEx'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='val_cpt_fin_ex',
            field=models.CharField(max_length=255, null=True, verbose_name='ValCptFinEx'),
        ),
        migrations.AlterField(
            model_name='sap',
            name='valeur_d_origine',
            field=models.CharField(max_length=255, null=True, verbose_name="Valeur d'origine"),
        ),
        migrations.AlterField(
            model_name='sap',
            name='valeur_man_patr',
            field=models.CharField(max_length=255, null=True, verbose_name='Valeur man. patr.'),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='account',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='agent_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='agent_namespace',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='agent_pod_name',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='agent_uuid',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='agent_version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='architecture',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='cloud_account',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='cloud_image',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='cloud_instance_id',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='cloud_instance_size',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='cloud_location',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='cloud_network',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='cloud_security_group',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='cloud_tags',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='cluster_name',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='console_migration_status',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='console_visible_ip',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='core_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='cpu_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='cpu_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='customer_identifier',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='decommissioned_at',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='device_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='disk_encryption',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='domain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='health_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='installer_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='ip_addresses',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='is_uninstalled',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='k8s_node_labels',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='k8s_node_name',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='k8s_type',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='k8s_version',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='last_active',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='last_logged_in_user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='last_reboot_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='last_reported_ip',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='locations',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='mac_addresses',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='management_connectivity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='memory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='model_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='network_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='operational_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='operational_state_expiration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='os',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='os_username',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='os_version',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='pending_uninstall',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='reboot_required_due_to_threat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='remote_profiling_expiration',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='remote_profiling_state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='scan_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='serial_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='site',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='storage_name',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='storage_type',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='subscribed_on',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='update_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='user_action_required',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sentinels',
            name='vulnerability_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sophos',
            name='computer_group',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophos',
            name='health_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophos',
            name='ip',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophos',
            name='last_active',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophos',
            name='last_user',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophos',
            name='os',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophos',
            name='protection',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sophos',
            name='tamper_protection',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('about_me', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
